# ---------------------------------------------------
# Default Configuration for the Deposit Application
# ---------------------------------------------------
#
# These values will be used unless overridden by environment variables
# or command-line arguments.

# Database File Paths
# The default file names for storing deposit and customer accounts.
db.deposits.file=deposits.ser
db.accounts.file=accounts.ser

# NBU (National Bank of Ukraine) Integration Settings 
# The interval, in milliseconds, at which the application will check for
# updated interest and tax rates from the NBU simulator.
# 5000 = 5 seconds
nbu.update.interval.ms=5000
